# Generated by Django 2.1.2 on 2018-11-28 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='课程顾问'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Course', verbose_name='咨询课程'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此客户是转介绍自内部学员,请在此处选择内部＼学员姓名', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_referral', to='repository.Customer', verbose_name='转介绍自学员'),
        ),
    ]
