# Generated by Django 2.1.2 on 2018-11-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181109_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name': '合同模板', 'verbose_name_plural': '合同模板'},
        ),
        migrations.RenameField(
            model_name='courserecord',
            old_name='course',
            new_name='from_class',
        ),
        migrations.AlterUniqueTogether(
            name='courserecord',
            unique_together={('from_class', 'day_num')},
        ),
    ]
