# Generated by Django 2.1.2 on 2018-11-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_taskpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'CRM账户', 'verbose_name_plural': 'CRM账户'},
        ),
    ]
