# Generated by Django 2.1.2 on 2018-11-25 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20181124_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskpermission',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='taskpermission',
            name='reported_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
