# Generated by Django 2.1.2 on 2018-11-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20181112_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyrecord',
            old_name='record',
            new_name='attendance',
        ),
    ]
