# Generated by Django 2.1.2 on 2018-11-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20181112_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('easyadmin_customers', '可以访问 客户库'), ('easyadmin_table_list', '可以访问 easyadmin 每个表的数据列表页'), ('easyadmin_table_index', '可以访问 easyadmin 首页'), ('easyadmin_table_list_view', '可以访问 easyadmin 每个表中对象的修改页'), ('easyadmin_table_list_change', '可以修改 easyadmin 每个表中对象'), ('easyadmin_table_list_action', '可以操作 每个表的 action 功能'), ('easyadmin_can_access_my_clients', '可以访问 自己的 客户列表')), 'verbose_name': 'CRM账户', 'verbose_name_plural': 'CRM账户'},
        ),
    ]
