# Generated by Django 2.1.2 on 2018-11-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_remove_taskpermission_reported_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('easy_admin_main_pg', '可以访问管理员主页'), ('app_tables', '可以查看所有APP'), ('this_table', '可以查看具体表'), ('table_add', '可以添加表'), ('table_modify', '可以修改表'), ('table_delete', '可以删除表')),
            },
        ),
        migrations.CreateModel(
            name='SalesPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('market_main_pg', '可以访问销售主页'), ('customers', '可以访问客户信息'), ('customer_modify', '可以修改客户信息'), ('enrollment', '可以访问帮助学员报名主页'), ('stu_enrollment', '可以查看学员报名表单模板')),
            },
        ),
        migrations.CreateModel(
            name='StudentPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('my_courses', '可以查看我的课程'), ('my_grade', '可以查看我的班级'), ('homework_detail', '可以查看作业信息'), ('delete_file', '可以删除作业'), ('my_homeworks', '可以提交作业')),
            },
        ),
        migrations.CreateModel(
            name='TeacherPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('teacher_main_pg', '可以访问讲师主页'), ('my_classes', '可以访问我的班级'), ('course_record', '可以访问上课记录'), ('view_class_stu_list', '可以访问学员列表')),
            },
        ),
        migrations.DeleteModel(
            name='TaskPermission',
        ),
    ]
