# Generated by Django 2.1.2 on 2018-11-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20181115_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'CRM账户', 'verbose_name_plural': 'CRM账户'},
        ),
    ]
