# Generated by Django 2.1.2 on 2018-11-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycrmadmin', '0001_initial'),
        ('repository', '0007_auto_20181115_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.ManyToManyField(to='easycrmadmin.TaskControl'),
        ),
    ]
