# Generated by Django 2.1.2 on 2018-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '动态权限存储类',
                'verbose_name_plural': '动态权限存储类',
                'permissions': (('view_task', 'View task'),),
            },
        ),
        migrations.CreateModel(
            name='TaskControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=128)),
                ('permission_type', models.CharField(choices=[('1', 'name'), ('2', 'url')], default='1', max_length=32)),
            ],
            options={
                'verbose_name': '权限配置表',
                'verbose_name_plural': '权限配置表',
            },
        ),
    ]
