# Generated by Django 2.1.2 on 2018-11-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycrmadmin', '0002_basepermission_dynamicpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasePermission',
        ),
        migrations.DeleteModel(
            name='DynamicPermission',
        ),
    ]
