# Generated by Django 2.1.2 on 2018-11-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycrmadmin', '0003_auto_20181115_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
