# Generated by Django 2.1.2 on 2018-11-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycrmadmin', '0004_basepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepermission',
            options={'verbose_name': '动态权限存储类', 'verbose_name_plural': '动态权限存储类'},
        ),
    ]
