# Generated by Django 2.1.2 on 2018-11-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
